// K-TEX Brand Constants
export const BRAND = {
  name: "K-TEX",
  tagline: "Premium Pakistani Menswear",
  description:
    "Experience the pinnacle of South Asian luxury. K-TEX merges centuries-old craftsmanship with modern silhouettes to create timeless menswear for the discerning gentleman.",
  email: "abdulwasay@khm.ae",
  phone: "03330557783",
  whatsapp: "03330557783",
  whatsappLink: "https://wa.me/923330557783",
  address: "KHM Group, Moza Dohala, Islamabad - Murree Expy, near Phulgran Toll Plaza, Islamabad",
  social: {
    instagram: "https://instagram.com/ktex",
    facebook: "https://facebook.com/ktex",
    youtube: "https://youtube.com/@ktex",
    pinterest: "https://pinterest.com/ktex",
  },
};

export const PROMO_MESSAGE = "Enjoy 20% OFF on New Arrivals — In Stores & Online";

export const SIZES = ["S", "M", "L", "XL", "XXL"] as const;

export const PLACEHOLDER_PRODUCTS = [
  {
    id: 1,
    name: "White Self Striped Formal Shirt",
    slug: "white-self-striped-formal-shirt",
    price: "8,290",
    salePrice: "",
    category: "formal-shirts",
    tags: ["new-arrivals", "mens-shirts", "mens"],
    fabric: "Cotton Blend",
    description: "A refined white self-striped formal shirt perfect for the modern professional. Crafted from premium cotton blend fabric with a structured fit.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/2_422bbc91-79f1-4967-9610-cd0aa11ada83.jpg?v=1744893498&width=600",
      "https://shopbrumano.com/cdn/shop/files/3_7f8b8a64-62c7-4ac1-8a1b-1f14bf48d9a7.jpg?v=1744893498&width=600",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#ffffff" },
      { name: "Light Blue", hex: "#B0D4F1" },
    ],
    stock: 25,
    badge: "",
  },
  {
    id: 2,
    name: "Olive Structured Polo With Cutaway Collar",
    slug: "olive-structured-polo-cutaway-collar",
    price: "5,290",
    salePrice: "",
    category: "mens-polos",
    tags: ["new-arrivals", "mens-polos", "mens"],
    fabric: "Pique Cotton",
    description: "A structured polo featuring a modern cutaway collar in olive green. Premium pique cotton construction for comfort and durability.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_e1a23c26-0c72-4c0a-af7e-e8cb1e95e0ab.jpg?v=1745497979&width=600",
      "https://shopbrumano.com/cdn/shop/files/2_7b3c3e79-2fb3-424e-9b96-45e684a69e90.jpg?v=1745497979&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Olive", hex: "#556B2F" },
    ],
    stock: 18,
    badge: "",
  },
  {
    id: 3,
    name: "Navy Blue Dobby Shirt",
    slug: "navy-blue-dobby-shirt",
    price: "4,392",
    salePrice: "5,490",
    category: "casual-shirts",
    tags: ["new-arrivals", "mens-shirts", "sale", "mens"],
    fabric: "Dobby Cotton",
    description: "A sophisticated navy blue dobby weave shirt with a subtle texture. Perfect for smart-casual occasions.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_7e8f19a8-68ec-43c5-87dd-c8c17ca1b40e.jpg?v=1745326587&width=600",
      "https://shopbrumano.com/cdn/shop/files/3_6fd7b6bf-3ee0-4e97-b39e-9a7b1e2d6c18.jpg?v=1745326587&width=600",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Navy Blue", hex: "#1B2A4A" },
    ],
    stock: 12,
    badge: "20% OFF",
  },
  {
    id: 4,
    name: "Dark Brown Drop Needle Flat Knit Polo",
    slug: "dark-brown-drop-needle-flat-knit-polo",
    price: "4,792",
    salePrice: "5,990",
    category: "mens-polos",
    tags: ["new-arrivals", "mens-polos", "sale", "mens"],
    fabric: "Flat Knit Cotton",
    description: "A luxurious dark brown flat knit polo with a distinctive drop needle texture. Elevated casual wear at its finest.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_5fecb4c6-4b32-40ad-bd0c-8ab3f67e8c12.jpg?v=1745411287&width=600",
      "https://shopbrumano.com/cdn/shop/files/2_d1a7e9f3-5c84-4f6b-b2e1-3d9c8a4f7e56.jpg?v=1745411287&width=600",
    ],
    sizes: ["M", "L", "XL"],
    colors: [
      { name: "Dark Brown", hex: "#3E2723" },
    ],
    stock: 8,
    badge: "20% OFF",
  },
  {
    id: 5,
    name: "Blue Self Striped Formal Shirt",
    slug: "blue-self-striped-formal-shirt",
    price: "8,290",
    salePrice: "",
    category: "formal-shirts",
    tags: ["new-arrivals", "mens-shirts", "mens"],
    fabric: "Premium Cotton",
    description: "An elegant blue self-striped formal shirt with impeccable tailoring. Ideal for boardroom meetings and formal occasions.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_b2c4d5e6-7a89-4f01-b234-5c6d7e8f9a01.jpg?v=1744893498&width=600",
      "https://shopbrumano.com/cdn/shop/files/3_a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d.jpg?v=1744893498&width=600",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Blue", hex: "#3B5998" },
    ],
    stock: 20,
    badge: "",
  },
  {
    id: 6,
    name: "White Raglan Sleeve Pique Sporty Polo",
    slug: "white-raglan-sleeve-pique-sporty-polo",
    price: "3,992",
    salePrice: "4,990",
    category: "mens-polos",
    tags: ["new-arrivals", "mens-polos", "sale", "mens"],
    fabric: "Pique Cotton",
    description: "A sporty white polo with raglan sleeves and pique texture. Perfect for an active lifestyle with premium comfort.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f.jpg?v=1745497979&width=600",
      "https://shopbrumano.com/cdn/shop/files/2_d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a.jpg?v=1745497979&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Navy", hex: "#1B2A4A" },
    ],
    stock: 15,
    badge: "20% OFF",
  },
  {
    id: 7,
    name: "Blue Striped Polo With Cutaway Collar",
    slug: "blue-striped-polo-cutaway-collar",
    price: "5,290",
    salePrice: "",
    category: "mens-polos",
    tags: ["new-arrivals", "mens-polos", "mens"],
    fabric: "Pique Cotton",
    description: "A classic blue striped polo with a modern cutaway collar. Timeless design meets contemporary tailoring.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_e5f6a7b8-9c0d-1e2f-3a4b-5c6d7e8f9a0b.jpg?v=1745497979&width=600",
      "https://shopbrumano.com/cdn/shop/files/2_f6a7b8c9-0d1e-2f3a-4b5c-6d7e8f9a0b1c.jpg?v=1745497979&width=600",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Blue", hex: "#4A90D9" },
    ],
    stock: 22,
    badge: "",
  },
  {
    id: 8,
    name: "White Structured Striped Formal Shirt",
    slug: "white-structured-striped-formal-shirt",
    price: "5,990",
    salePrice: "",
    category: "formal-shirts",
    tags: ["new-arrivals", "mens-shirts", "mens"],
    fabric: "Structured Cotton",
    description: "A premium white structured striped formal shirt with a contemporary fit. The perfect addition to your professional wardrobe.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_a7b8c9d0-1e2f-3a4b-5c6d-7e8f9a0b1c2d.jpg?v=1744893498&width=600",
      "https://shopbrumano.com/cdn/shop/files/3_b8c9d0e1-2f3a-4b5c-6d7e-8f9a0b1c2d3e.jpg?v=1744893498&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
    ],
    stock: 30,
    badge: "",
  },
  {
    id: 9,
    name: "Charcoal Slim Fit Chino Trousers",
    slug: "charcoal-slim-fit-chino-trousers",
    price: "6,490",
    salePrice: "",
    category: "chino-trousers",
    tags: ["new-arrivals", "mens-trousers", "mens"],
    fabric: "Stretch Cotton Twill",
    description: "Sleek charcoal chinos with a modern slim fit. Crafted from stretch cotton twill for all-day comfort.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/2_422bbc91-79f1-4967-9610-cd0aa11ada83.jpg?v=1744893498&width=600",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [{ name: "Charcoal", hex: "#36454F" }],
    stock: 35,
    badge: "",
  },
  {
    id: 10,
    name: "Burgundy Quilted Jacket",
    slug: "burgundy-quilted-jacket",
    price: "14,990",
    salePrice: "",
    category: "quilted-jackets",
    tags: ["mens-jackets", "mens"],
    fabric: "Quilted Polyester",
    description: "A premium burgundy quilted jacket with gold-tone hardware. Perfect for transitional weather.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_e1a23c26-0c72-4c0a-af7e-e8cb1e95e0ab.jpg?v=1745497979&width=600",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Burgundy", hex: "#800020" }],
    stock: 10,
    badge: "",
  },
  {
    id: 11,
    name: "Navy Blue Formal Blazer",
    slug: "navy-blue-formal-blazer",
    price: "22,990",
    salePrice: "",
    category: "formal-blazers",
    tags: ["mens-blazers", "mens"],
    fabric: "Wool Blend",
    description: "A classic navy formal blazer tailored from premium wool blend. The cornerstone of every gentleman's wardrobe.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_7e8f19a8-68ec-43c5-87dd-c8c17ca1b40e.jpg?v=1745326587&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy", hex: "#1B2A4A" }],
    stock: 7,
    badge: "",
  },
  {
    id: 12,
    name: "Cream V-Neck Sweater",
    slug: "cream-vneck-sweater",
    price: "7,290",
    salePrice: "9,990",
    category: "vneck-sweaters",
    tags: ["mens-sweaters", "sale", "mens"],
    fabric: "Merino Wool Blend",
    description: "A luxuriously soft cream V-neck sweater in merino wool blend. Perfect layering piece for cooler days.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_5fecb4c6-4b32-40ad-bd0c-8ab3f67e8c12.jpg?v=1745411287&width=600",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Cream", hex: "#FFFDD0" }],
    stock: 14,
    badge: "27% OFF",
  },
  {
    id: 13,
    name: "Black Graphic T-Shirt",
    slug: "black-graphic-tshirt",
    price: "3,290",
    salePrice: "",
    category: "graphic-tshirts",
    tags: ["new-arrivals", "mens-tshirts", "mens"],
    fabric: "Combed Cotton Jersey",
    description: "A bold black graphic tee with contemporary artwork. Premium combed cotton for a buttery soft feel.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_b2c4d5e6-7a89-4f01-b234-5c6d7e8f9a01.jpg?v=1744893498&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 40,
    badge: "",
  },
  {
    id: 14,
    name: "Grey Bomber Jacket",
    slug: "grey-bomber-jacket",
    price: "11,990",
    salePrice: "14,990",
    category: "bomber-jackets",
    tags: ["mens-jackets", "sale", "mens"],
    fabric: "Nylon Shell / Polyester Lining",
    description: "A modern grey bomber jacket with ribbed cuffs and collar. Versatile outerwear for any occasion.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f.jpg?v=1745497979&width=600",
    ],
    sizes: ["M", "L", "XL"],
    colors: [{ name: "Grey", hex: "#808080" }],
    stock: 6,
    badge: "20% OFF",
  },
  {
    id: 15,
    name: "Beige Dress Pants",
    slug: "beige-dress-pants",
    price: "7,490",
    salePrice: "",
    category: "dress-pants",
    tags: ["new-arrivals", "mens-trousers", "mens"],
    fabric: "Stretch Wool Blend",
    description: "Impeccably tailored beige dress pants in stretch wool blend. Designed for the modern professional.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_e5f6a7b8-9c0d-1e2f-3a4b-5c6d7e8f9a0b.jpg?v=1745497979&width=600",
    ],
    sizes: ["30", "32", "34", "36"],
    colors: [{ name: "Beige", hex: "#F5F5DC" }],
    stock: 18,
    badge: "",
  },
  {
    id: 16,
    name: "Olive Oversized T-Shirt",
    slug: "olive-oversized-tshirt",
    price: "2,990",
    salePrice: "",
    category: "oversized-tshirts",
    tags: ["new-arrivals", "mens-tshirts", "mens"],
    fabric: "Heavy Cotton Jersey",
    description: "A relaxed olive oversized tee with dropped shoulders. The perfect streetwear essential.",
    images: [
      "https://shopbrumano.com/cdn/shop/files/1_a7b8c9d0-1e2f-3a4b-5c6d-7e8f9a0b1c2d.jpg?v=1744893498&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Olive", hex: "#556B2F" }],
    stock: 28,
    badge: "",
  },
];

export const PLACEHOLDER_REVIEWS = [
  {
    id: 1,
    name: "Anonymous",
    rating: 5,
    text: "Brumano products are of outstanding quality and are truly worth the price.",
    product: "Charcoal Bomber Jacket",
    date: "2026-03-15",
  },
  {
    id: 2,
    name: "Umair Younas",
    rating: 5,
    text: "A real brand. Experience from unboxing to wearing was good. Recommended",
    product: "",
    date: "2026-03-10",
  },
  {
    id: 3,
    name: "Muhammad Abdullah Khan",
    rating: 5,
    text: "Great fabric, great color and perfect size",
    product: "",
    date: "2026-02-28",
  },
  {
    id: 4,
    name: "Subhan Ayaz",
    rating: 5,
    text: "Best quality and budget",
    product: "",
    date: "2026-02-20",
  },
  {
    id: 5,
    name: "Mohammad Akabir",
    rating: 5,
    text: "Excellent quality.",
    product: "",
    date: "2026-02-15",
  },
  {
    id: 6,
    name: "Obaid",
    rating: 4,
    text: "Good buy 👍",
    product: "",
    date: "2026-02-10",
  },
];
